version: "3"

services:
  journo:
    init: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:11000:80
      - 127.0.0.1:11001:8080
    env_file:
      - ./frontend/.env
      - ./backend/.env
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: postgres:15
    ports:
      - 127.0.0.1:11002:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: public
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
