version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:11000:80
    env_file: ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:11001:8080
    env_file: ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - 127.0.0.1:11002:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: public
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: